version: '3.8'

services:
  frontend:
    image: blog-frontend  # Replace with the image name of your production app
    ports:
      - "80:80"  # Expose port 80 to access the app
    networks:
      - app-network
    env_file:
      - .env  # Use the .env file from your host machine for the production service
  
  backend:
    image: blog-backend  # Replace with the image name of your development app
    ports:
      - "5004:5004"  # Expose port 5004 to access the dev server
    command: npm start  # Start the development server (or any other command you use)
    volumes:
      - ../BLOG_BACKEND/:/app  # Mount the current directory to allow live code updates
      - ../Blog_Backend/.env:/app/.env  # Mount the .env file into the container for development
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
